// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	core "datingapp/application/core"

	mock "github.com/stretchr/testify/mock"
)

// ICredentialUseCase is an autogenerated mock type for the ICredentialUseCase type
type ICredentialUseCase struct {
	mock.Mock
}

// RegisterCredential provides a mock function with given fields: request
func (_m *ICredentialUseCase) RegisterCredential(request core.CredentialRequest) error {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for RegisterCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(core.CredentialRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewICredentialUseCase creates a new instance of ICredentialUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICredentialUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICredentialUseCase {
	mock := &ICredentialUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
