// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	core "datingapp/application/core"

	mock "github.com/stretchr/testify/mock"
)

// ICredentialRepository is an autogenerated mock type for the ICredentialRepository type
type ICredentialRepository struct {
	mock.Mock
}

// GetCredentials provides a mock function with given fields: phoneNumber
func (_m *ICredentialRepository) GetCredentials(phoneNumber string) (*core.Credentials, error) {
	ret := _m.Called(phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentials")
	}

	var r0 *core.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*core.Credentials, error)); ok {
		return rf(phoneNumber)
	}
	if rf, ok := ret.Get(0).(func(string) *core.Credentials); ok {
		r0 = rf(phoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Credentials)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(phoneNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertCredentials provides a mock function with given fields: _a0
func (_m *ICredentialRepository) InsertCredentials(_a0 core.Credentials) (core.Credentials, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for InsertCredentials")
	}

	var r0 core.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(core.Credentials) (core.Credentials, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(core.Credentials) core.Credentials); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(core.Credentials)
	}

	if rf, ok := ret.Get(1).(func(core.Credentials) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICredentialRepository creates a new instance of ICredentialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICredentialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICredentialRepository {
	mock := &ICredentialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
