// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	core "datingapp/application/core"

	mock "github.com/stretchr/testify/mock"
)

// IProfileRepository is an autogenerated mock type for the IProfileRepository type
type IProfileRepository struct {
	mock.Mock
}

// GetUserProfile provides a mock function with given fields: profileID
func (_m *IProfileRepository) GetUserProfile(profileID int) (core.Profile, error) {
	ret := _m.Called(profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 core.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (core.Profile, error)); ok {
		return rf(profileID)
	}
	if rf, ok := ret.Get(0).(func(int) core.Profile); ok {
		r0 = rf(profileID)
	} else {
		r0 = ret.Get(0).(core.Profile)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertNewProfile provides a mock function with given fields: profile
func (_m *IProfileRepository) InsertNewProfile(profile core.Profile) (core.Profile, error) {
	ret := _m.Called(profile)

	if len(ret) == 0 {
		panic("no return value specified for InsertNewProfile")
	}

	var r0 core.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(core.Profile) (core.Profile, error)); ok {
		return rf(profile)
	}
	if rf, ok := ret.Get(0).(func(core.Profile) core.Profile); ok {
		r0 = rf(profile)
	} else {
		r0 = ret.Get(0).(core.Profile)
	}

	if rf, ok := ret.Get(1).(func(core.Profile) error); ok {
		r1 = rf(profile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIProfileRepository creates a new instance of IProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProfileRepository {
	mock := &IProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
