// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	core "datingapp/application/core"

	mock "github.com/stretchr/testify/mock"
)

// ISessionRepository is an autogenerated mock type for the ISessionRepository type
type ISessionRepository struct {
	mock.Mock
}

// GetSessionsByPhone provides a mock function with given fields: phoneNumber
func (_m *ISessionRepository) GetSessionsByPhone(phoneNumber string) ([]core.Session, error) {
	ret := _m.Called(phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionsByPhone")
	}

	var r0 []core.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]core.Session, error)); ok {
		return rf(phoneNumber)
	}
	if rf, ok := ret.Get(0).(func(string) []core.Session); ok {
		r0 = rf(phoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(phoneNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitiateLogin provides a mock function with given fields: session
func (_m *ISessionRepository) InitiateLogin(session core.Session) error {
	ret := _m.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for InitiateLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(core.Session) error); ok {
		r0 = rf(session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: session
func (_m *ISessionRepository) Login(session core.Session) (core.Session, error) {
	ret := _m.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 core.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(core.Session) (core.Session, error)); ok {
		return rf(session)
	}
	if rf, ok := ret.Get(0).(func(core.Session) core.Session); ok {
		r0 = rf(session)
	} else {
		r0 = ret.Get(0).(core.Session)
	}

	if rf, ok := ret.Get(1).(func(core.Session) error); ok {
		r1 = rf(session)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewISessionRepository creates a new instance of ISessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISessionRepository {
	mock := &ISessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
