// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	core "datingapp/application/core"

	mock "github.com/stretchr/testify/mock"
)

// ISessionUseCase is an autogenerated mock type for the ISessionUseCase type
type ISessionUseCase struct {
	mock.Mock
}

// InitiateLogin provides a mock function with given fields: request
func (_m *ISessionUseCase) InitiateLogin(request core.InitiateLoginRequest) error {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for InitiateLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(core.InitiateLoginRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: request
func (_m *ISessionUseCase) Login(request core.LoginRequest) (string, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(core.LoginRequest) (string, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(core.LoginRequest) string); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(core.LoginRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewISessionUseCase creates a new instance of ISessionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISessionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISessionUseCase {
	mock := &ISessionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
