// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	core "datingapp/application/core"

	mock "github.com/stretchr/testify/mock"
)

// ISessionTokenProvider is an autogenerated mock type for the ISessionTokenProvider type
type ISessionTokenProvider struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: session
func (_m *ISessionTokenProvider) GenerateToken(session core.Session) (core.SessionToken, error) {
	ret := _m.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 core.SessionToken
	var r1 error
	if rf, ok := ret.Get(0).(func(core.Session) (core.SessionToken, error)); ok {
		return rf(session)
	}
	if rf, ok := ret.Get(0).(func(core.Session) core.SessionToken); ok {
		r0 = rf(session)
	} else {
		r0 = ret.Get(0).(core.SessionToken)
	}

	if rf, ok := ret.Get(1).(func(core.Session) error); ok {
		r1 = rf(session)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewISessionTokenProvider creates a new instance of ISessionTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISessionTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISessionTokenProvider {
	mock := &ISessionTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
