// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	core "datingapp/application/core"

	mock "github.com/stretchr/testify/mock"
)

// IUserProfileUseCase is an autogenerated mock type for the IUserProfileUseCase type
type IUserProfileUseCase struct {
	mock.Mock
}

// RegisterUserProfile provides a mock function with given fields: userProfile
func (_m *IUserProfileUseCase) RegisterUserProfile(userProfile core.UserProfile) error {
	ret := _m.Called(userProfile)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUserProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(core.UserProfile) error); ok {
		r0 = rf(userProfile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIUserProfileUseCase creates a new instance of IUserProfileUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserProfileUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserProfileUseCase {
	mock := &IUserProfileUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
